[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_stake_program = "76r9WYEaYgLcsvbvZaEgNkhiu7pP7XK9m3HfY6nQ7JRc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/fadex/.config/solana/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
